version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "automerge"
    reviewers:
      - "krishnakorukanti"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Next.js is locked to a specific version for ContentLayer compatibility
      - dependency-name: "next"
      - dependency-name: "next-contentlayer"
      - dependency-name: "contentlayer"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "automerge" 